---
title: "HPCX Ondemand User Documentation"
subtitle: "Our University's Web-based access to HPC"
---

## What is HPCX Ondemand {#introduction}

HPCX Ondemand is a secure browser-based interface for accessing HPCX. This service is built on [Open OnDemand](https://openondemand.org), a widely used HPC tool for visualization, interactive computing, and teaching. [Open OnDemand](https://openondemand.org) is funded by the National Science Foundation (NSF) and developed by the Ohio Supercomputer Center. It provides users with convenient access to high-performance computing (HPC) resources and filesystems directly through a web browser. Key features of OOD include:

- File management: upload, download, and edit files seamlessly.
- Job submission and monitoring: efficiently manage computing tasks.
- Graphical application access: run and interact with graphical HPC applications.
- Command-line access: use the terminal interface for advanced operations.
At the University, OOD is available for use on the amd/l4 partition of HPCX at the first instance, with other clusters to be added in the future.

## Core Features

- **Web Access**

Open OnDemand eliminates the need for client software installations by providing web access to high-performance computing (HPC) resources. This feature allows users to interact with HPC systems directly through their web browsers, making it easier to submit and monitor jobs, manage files, and run applications from any location. The intuitive interface enhances accessibility and convenience for a broader audience.

- **File Management**

Open OnDemand includes file management capabilities, allowing users to upload, download, and organize their files within a HPC environment. It supports drag-and-drop functionality, making it simple to transfer files between local and remote systems. Users can create directories, move files, and set permissions, all through a web interface. 
 
- **Job Submission and Management**

Open OnDemand simplifies job submission and management, making it accessible and efficient for users of all experience levels. This feature allows users to submit computational jobs to HPC systems directly through their web browsers, eliminating the need for command-line interactions. The web-based interface enables users to select job parameters, monitor progress in real-time, and manage jobs with ease. 

- **Interactive Applications**

Open OnDemand enhances user experience by supporting interactive applications directly within the web browser. This core feature allows users to run and interact with applications such as Jupyter Notebook, RStudio, Desktop, and MATLAB without needing to install any additional software. The platform provides a seamless interface for launching these applications, enabling users to perform data analysis, visualization, and other computational tasks interactively. 

- **Shell Access**

Open OnDemand facilitates shell development by providing users with direct access to Iridis X login node through a web browser. This core feature allows users to execute command-line operations on HPC without needing to install any additional software. The web-based shell interface supports a wide range of tasks, including file manipulation, script execution, and system monitoring. 

